site_name: Watsonx.data Lab
# theme:
#   name: material
nav:
  - Introduction: "wxd-intro.md"
  - Quick Start: "wxd-quick.md"
  - How to Reference:
    - Requesting an image: "wxd-reference-techzone.md"
    - Accessing the reservation: "wxd-reference-access.md"
    - VPN Access with Wireguard: "wxd-reference-wireguard.md"
    - VNC Basics: "wxd-reference-vnc.md"
    - SSH and SCP Commands: "wxd-reference-ssh.md"
    - Available Ports: "wxd-reference-ports.md"
    - Userids and Passwords: "wxd-reference-passwords.md"
    - Portainer Console: "wxd-reference-portainer.md"
  - Check Server Status: "wxd-startwatsonx.md"
  - Introduction: 
    - Presto CLI: "wxd-prestocli.md"
    - Watsonx.data UI: "wxd-watsonui.md"
    - Presto UI: "wxd-presto.md"
    - MinIO UI: "wxd-minio.md"
    - dBeaver: "wxd-dbeaver.md"
  - Presto SQL:
    - Analytic Workloads: "wxd-analytics.md"
    - Advanced Functions: "wxd-advanced.md"
    - Time Travel: "wxd-timetravel.md"
    - Federation: "wxd-federation.md"
    - Apache Superset: "wxd-superset.md"
  - Working with Object Store Buckets: "wxd-objectstore.md"
  - Troubleshooting: "wxd-troubleshooting.md"
  - Datasets: "wxd-datasets.md"
  - Appendix: 
    - Disclaimer: "wxd-disclaimer.md"
    - Revisions: "wxd-revisions.md"
    - Acknowledgements: "wxd-acknowledgements.md"

  # Copyright
copyright: Copyright &copy; 2023 IBM 

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  logo: wxd-images/IBM_logo®_rev_RGB.png  
  palette:
    scheme: default
    primary: black
    accent: black